version: '3'

# TODO manage via Ansible
services:
  gui:
    user: node
    build:
      context: .
      dockerfile: ./apps/gui/Dockerfile
    env_file: variables/.env.gui
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run serve:gui

  bastion:
    user: node
    build:
      context: .
      dockerfile: ./apps/bastion/Dockerfile
    env_file: variables/.env.bastion
    ports:
      - 4001:4001
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run serve:bastion

  user-service:
    user: node
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    env_file: variables/.env.user
    ports:
      - 4002:4002
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run serve:user
